"""add created_at fields

Revision ID: b5db575795c4
Revises: ca42297a1d70
Create Date: 2025-04-11 17:51:42.469626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5db575795c4'
down_revision = 'ca42297a1d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('classification', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
